[plugins.slbot-plugin]
guild_id = 842465969469522001

[[plugins.slbot-plugin.commands]]
name = "about"
description = "Affiche les informations"
message = '''
        Ce bot a pour but de gérer et de simplifier certains processus sur le serveur Discord de Support-Launcher.
        Il va téléverser automatiquement les fichiers sur Hastebin (peut être évité en écrivant `--ignore` dans le message).
        '''
embed = { title = "À propos", color = 3447003 }

[[plugins.slbot-plugin.commands]]
name = "ask"
description = "Don't ask to ask"
message = '''
        Cela ne sert à rien de demander pour de l'aide. Pour bien poser une question il faut poser la question en détaillant bien le problème.
        S'il y a du code ou une erreur, il faut fournir les 2 afin que l'on puisse t'aider au mieux.
        Donc au lieu de dire:
        > J'ai besoin d'aide
        Il est préférable de dire:
        > J'ai un soucis avec *blabla...*
        > voici mon code:
        > > `code`
        > voici l'erreur
        > > `erreur`
        *Lien: https://dontasktoask.com/*
        '''
embed = { title = "Don't ask to ask", color = 3447003 }

[[plugins.slbot-plugin.commands]]
name = "googleit"
description = "Envoie un GIF"
message = "https://tenor.com/view/edna-mode-gooble-google-gooble-it-gif-12159251"

[[plugins.slbot-plugin.commands]]
name = "learnjava"
description = "Envoie un GIF"
message = "https://tenor.com/view/supportlauncher-bird-learn-fucking-java-learn-java-java-gif-17649710"

[[plugins.slbot-plugin.commands]]
name = "packs"
description = "Lien vers les differents packs Minecraft"
message = '''
        Voici le lien vers les différents packs Minecraft disponibles:
        https://packs.alwyn974.re/
        '''
embed = { title = "Packs minecraft", color = 3447003 }

[[plugins.slbot-plugin.commands]]
name = "versions"
description = "Équivalence des versions"
message = '''
        Chaque version de Minecraft a besoin d'une version spécifique de Java. Voici la liste des équivalences:
        - jusqu'à `1.12.2` (incluse) -> Java 8 (=1.8)
        - de `1.13` à `1.16.5` vanilla -> Java 8 et 11
        - de `1.13` à `1.16.5` forge -> Java 8
        - `1.17` -> Java 16
        - `1.18` et `1.19` -> Java 17
        '''
embed = { title = "Équivalence des versions Minecraft/Java", color = 3447003 }



[[plugins.slbot-plugin.commands]]
name = "haste"
description = "Téléverser un fichier sur HasteBin"
message = ":warning: Si ton code est trop long, ne l'envoie pas directement sur discord, passe par ce site: https://code.litarvan.com/"
embed = { title = "HasteBin", color = 3447003 }